services:
  rabbitmq:
    image: rabbitmq:3-management
    command: rabbitmq-server
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
